# Starship Prompt Configuration
add_newline = false

[character]
success_symbol = "➜ "
error_symbol = "✗ "

[git_branch]
format = "on [$symbol$branch]($style) "

[nodejs]
format = "via [$symbol$version]($style) "
detect_extensions = ["js", "mjs", "ts", "tsx", "cts", "mts"]

[python]
format = 'via [${symbol}${pyenv_prefix}(${version})( \\($virtualenv\\))]($style) '

[directory]
truncation_length = 3
truncate_to_repo = true